//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schdeuler.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysedDirectory
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public long AnalyseTypeId { get; set; }
    
        public virtual AnalyseType AnalyseType { get; set; }
    }
}
