//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schdeuler.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBVersion
    {
        public int Version { get; set; }
        public System.DateTime UpgradeDate { get; set; }
        public string Comment { get; set; }
    }
}
