//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schdeuler.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledTask
    {
        public long Id { get; set; }
        public System.DateTime PlanedExecutionDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<long> RelatedObjectId { get; set; }
        public long ScheduledTaskTypeId { get; set; }
        public long ScheduledTaskStateId { get; set; }
    
        public virtual ScheduledTaskState ScheduledTaskState { get; set; }
        public virtual ScheduledTaskType ScheduledTaskType { get; set; }
    }
}
