//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schdeuler.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulerDBEntities : DbContext
    {
        public SchedulerDBEntities()
            : base("name=SchedulerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DBVersion> DBVersion { get; set; }
        public virtual DbSet<ScheduledTaskState> ScheduledTaskStates1 { get; set; }
        public virtual DbSet<ScheduledTaskType> ScheduledTaskTypes1 { get; set; }
        public virtual DbSet<User> Users1 { get; set; }
        public virtual DbSet<ScheduledTask> ScheduledTasks { get; set; }
        public virtual DbSet<AnalysedDirectory> AnalysedDirectories { get; set; }
        public virtual DbSet<AnalyseType> AnalyseTypes { get; set; }
    }
}
